spring-boot-plus:
  # 是否启用ansi控制台输出有颜色的字体，dev环境建议开启，服务器环境设置为false
  enable-ansi: true
  # 当前环境服务IP地址
  server-ip: 127.0.0.1
  # 文件上传下载配置
  upload-path: /opt/upload/


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/file_pool_020?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  # Redis配置
  redis:
    database: 1
    host: 127.0.0.1
    password: 123456
    port: 6379

#云钱包接口地址
cloud:
  url: 'http://192.168.1.12:8887/api/wallet/'

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#美联短信配置
meilian:
  apikey: '7fe82737255611e5f0611c1731ec58de'
  username: 'junke_hb'
  pwd_md5: '790e3e5f52381edbc811155ffffe6c36'
  sign: '【联盈云矿】'

#邮件短信配置
email:
  userName: oip13824335466@163.com
  password: WHCYPMXXNTXPJMOR
  subject: 【联盈云矿】服务通知
  fromname: 联盈云矿
  hostName: smtp.163.com

#文件上传配置
upload:
  #启用 1为阿里oss 2为华为obs
  active: 2
  aliyun:
    oss:
      endpoint: 'https://oss-cn-shenzhen.aliyuncs.com'
      accessKeyId: 'LTAI4FzAe21xQF3qZZy1xccL'
      accessKeySecret: 'XgiGsXsEJQx4O2LQx4MgEjYRlIaBES'
      endpoint_get: 'https://xstc-cc.oss-cn-shenzhen.aliyuncs.com'
      bucketName: 'xstc-cc'
  huaweicloud:
    obs:
      endPoint: https://obs.cn-south-1.myhuaweicloud.com
      ak: F2QV7ARSFMHPLASWTZSK
      sk: KKnfc1fTM375LZln2xIpgOfkV5U1uaje5xbNKH0S
      bucketname: crypto
#xxl-job 配置
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8836/xxl-job-admin
    accessToken:
    executor:
      appname: "fil-pool-13"
      address:
      ip: 192.168.1.61
      port: 10005
      logpath: logs/xxl-job/jobhandler
      logretentiondays: 3
