spring-boot-plus:
  # 是否启用ansi控制台输出有颜色的字体，dev环境建议开启，服务器环境设置为false
  enable-ansi: true
  # 当前环境服务IP地址
  server-ip: 94.74.99.147
  # 文件上传下载配置
  upload-path: /opt/upload/


spring:
  datasource:
    url: jdbc:mysql://192.168.0.2:3306/filpool_013?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: XrbTNwCcWhmKKH3V

  # Redis配置
  redis:
    database: 13
    host: 192.168.0.164
    password: yWQmOHNjRj9y3whC
    port: 6379

#云钱包接口地址
cloud:
  url: 'http://192.168.0.131:8888/api/wallet/'

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#美联短信配置
meilian:
  apikey: 'fe7f31a48d6dd1902ede6ab0d9d2071d'
  username: 'xts_hy'
  pwd_md5: 'e6a350411d47bc453e094ee3613869b1'
  sign: '【加密云储】'

#邮件短信配置
email:
  userName: yunshangjiami@163.com
  password: SSTQDRCILQUPBDQB
  subject: 【加密云储】服务通知
  fromname: 加密云储
  hostName: smtp.163.com

#文件上传配置
upload:
  #启用 1为阿里oss 2为华为obs
  active: 2
  aliyun:
    oss:
      endpoint: 'https://oss-cn-shenzhen.aliyuncs.com'
      accessKeyId: 'LTAI4FzAe21xQF3qZZy1xccL'
      accessKeySecret: 'XgiGsXsEJQx4O2LQx4MgEjYRlIaBES'
      endpoint_get: 'https://xstc-cc.oss-cn-shenzhen.aliyuncs.com'
      bucketName: 'xstc-cc'
  huaweicloud:
    obs:
      endPoint: https://obs.cn-south-1.myhuaweicloud.com
      ak: F2QV7ARSFMHPLASWTZSK
      sk: KKnfc1fTM375LZln2xIpgOfkV5U1uaje5xbNKH0S
      bucketname: crypto
#xxl-job 配置
xxl:
  job:
    admin:
      addresses: http://192.168.0.131:7090/xxl-job-admin
    accessToken:
    executor:
      appname: "fil-pool-13"
      address:
      ip: 192.168.0.131
      port: 10090
      logpath: logs/xxl-job/jobhandler
      logretentiondays: 3
