version: "3"
services:
  xxl-job-admin:
    container_name: xxl-job-admin-2.3.0
    image: registry.cn-hongkong.aliyuncs.com/starcounting/xxl-job:2.3.0
    ports:
      - 7093:8080
    volumes:
      - ./logs:/data/applogs
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://192.168.1.61:3307/xxl_job_fil?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=root --xxl.job.logretentiondays=3"
    restart: on-failure
